INSERT INTO exam_definition (id, subject_abbreviation, exam_session, duration_minutes, type, note)
VALUES
    ('АПС-СЕПТЕМВРИ', 'APS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ФИЗ-СЕПТЕМВРИ', 'FIZ', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДС-СЕПТЕМВРИ', 'DS', 'SEPTEMBER', 90, 'LAB', ''),
    ('КЕ-СЕПТЕМВРИ', 'KE', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВП-СЕПТЕМВРИ', 'WP', 'SEPTEMBER', 90, 'LAB', ''),
    ('СП-СЕПТЕМВРИ', 'SP', 'SEPTEMBER', 90, 'LAB', ''),
    ('АДИС-СЕПТЕМВРИ', 'ADIS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ЛАП-СЕПТЕМВРИ', 'LAP', 'SEPTEMBER', 90, 'LAB', ''),
    ('ЕИКТИ-СЕПТЕМВРИ', 'EIKTI', 'SEPTEMBER', 90, 'LAB', ''),
    ('ШДКИ-СЕПТЕМВРИ', 'SDKI', 'SEPTEMBER', 90, 'LAB', ''),
    ('МИС-СЕПТЕМВРИ', 'MIS', 'SEPTEMBER', 90, 'LAB', ''),
    ('МПИП-СЕПТЕМВРИ', 'MPIP', 'SEPTEMBER', 90, 'LAB', ''),
    ('АНС-СЕПТЕМВРИ', 'ANS', 'SEPTEMBER', 90, 'LAB', ''),
    ('БМ-СЕПТЕМВРИ', 'BM', 'SEPTEMBER', 90, 'LAB', ''),
    ('МИКРОСМИ-СЕПТЕМВРИ', 'MIKROSMI', 'SEPTEMBER', 90, 'LAB', ''),
    ('КМ-СЕПТЕМВРИ', 'KM', 'SEPTEMBER', 90, 'LAB', ''),
    ('ИИКТ-СЕПТЕМВРИ', 'IIKT', 'SEPTEMBER', 90, 'LAB', ''),
    ('ММ-СЕПТЕМВРИ', 'MM', 'SEPTEMBER', 90, 'LAB', ''),
    ('КМБ-СЕПТЕМВРИ', 'KMB', 'SEPTEMBER', 90, 'LAB', ''),
    ('ИССОК-СЕПТЕМВРИ', 'ISSOK', 'SEPTEMBER', 90, 'LAB', ''),
    ('ПДП-СЕПТЕМВРИ', 'PDP', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДМ-СЕПТЕМВРИ', 'DM', 'SEPTEMBER', 90, 'LAB', ''),
    ('ОР-СЕПТЕМВРИ', 'OP', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДОС-СЕПТЕМВРИ', 'DOS', 'SEPTEMBER', 90, 'LAB', ''),
    ('НВД-СЕПТЕМВРИ', 'NVD', 'SEPTEMBER', 90, 'LAB', ''),
    ('КАЛК1-СЕПТЕМВРИ', 'KALK1', 'SEPTEMBER', 90, 'LAB', ''),
    ('НП-СЕПТЕМВРИ', 'NP', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВБС-СЕПТЕМВРИ', 'WBS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ИПКС-СЕПТЕМВРИ', 'IPKS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДС1-СЕПТЕМВРИ', 'DS1', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВНП-СЕПТЕМВРИ', 'VNP', 'SEPTEMBER', 90, 'LAB', ''),
    ('МАТ1-СЕПТЕМВРИ', 'MAT1', 'SEPTEMBER', 90, 'LAB', ''),
    ('МУЛТСМИ-СЕПТЕМВРИ', 'MULTISMI', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВКОМПН-СЕПТЕМВРИ', 'VKOMPS', 'SEPTEMBER', 90, 'LAB', ''),
    ('СВС-СЕПТЕМВРИ', 'SVS', 'SEPTEMBER', 90, 'LAB', ''),
    ('НИЧК-СЕПТЕМВРИ', 'NICK', 'SEPTEMBER', 90, 'LAB', ''),
    ('ПР-СЕПТЕМВРИ', 'PR', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВИС-СЕПТЕМВРИ', 'VIS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДИАС-СЕПТЕМВРИ', 'DIAS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДДИГК-СЕПТЕМВРИ', 'DDIGK', 'SEPTEMBER', 90, 'LAB', ''),
    ('БП-СЕПТЕМВРИ', 'DB', 'SEPTEMBER', 90, 'LAB', ''),
    ('ОТИ-СЕПТЕМВРИ', 'OTI', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВБИ-СЕПТЕМВРИ', 'VBI', 'SEPTEMBER', 90, 'LAB', ''),
    ('УТП-СЕПТЕМВРИ', 'UTP', 'SEPTEMBER', 90, 'LAB', ''),
    ('ОВД-СЕПТЕМВРИ', 'OVD', 'SEPTEMBER', 90, 'LAB', ''),
    ('КГ-СЕПТЕМВРИ', 'KG', 'SEPTEMBER', 90, 'LAB', ''),
    ('ИС-СЕПТЕМВРИ', 'IS', 'SEPTEMBER', 90, 'LAB', ''),
    ('УИКТП-СЕПТЕМВРИ', 'UIKTP', 'SEPTEMBER', 90, 'LAB', ''),
    ('КВРШ-СЕПТЕМВРИ', 'KVRS', 'SEPTEMBER', 90, 'LAB', ''),
    ('КИИ-СЕПТЕМВРИ', 'DEVOPS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ИТ-СЕПТЕМВРИ', 'IT', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДНА-СЕПТЕМВРИ', 'DNA', 'SEPTEMBER', 90, 'LAB', ''),
    ('КАЛК2-СЕПТЕМВРИ', 'KALK2', 'SEPTEMBER', 90, 'LAB', ''),
    ('ООАД-СЕПТЕМВРИ', 'OOAD', 'SEPTEMBER', 90, 'LAB', ''),
    ('НБП-СЕПТЕМВРИ', 'NBP', 'SEPTEMBER', 90, 'LAB', ''),
    ('ООП-СЕПТЕМВРИ', 'OOP', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВКН-СЕПТЕМВРИ', 'VKN', 'SEPTEMBER', 90, 'LAB', ''),
    ('АНМ-СЕПТЕМВРИ', 'ANM', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВИЗПРОГ-СЕПТЕМВРИ', 'VIZPROG', 'SEPTEMBER', 90, 'LAB', ''),
    ('МУ-СЕПТЕМВРИ', 'MY', 'SEPTEMBER', 90, 'LAB', ''),
    ('ЕВЛАД-СЕПТЕМВРИ', 'EVLAD', 'SEPTEMBER', 90, 'LAB', ''),
    ('ФЈА-СЕПТЕМВРИ', 'FJA', 'SEPTEMBER', 90, 'LAB', ''),
    ('ПРЕТПР-СЕПТЕМВРИ', 'PRETPR', 'SEPTEMBER', 90, 'LAB', ''),
    ('МИК-СЕПТЕМВРИ', 'MIK', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДКМ-СЕПТЕМВРИ', 'DKM', 'SEPTEMBER', 90, 'LAB', ''),
    ('КИО-СЕПТЕМВРИ', 'KIO', 'SEPTEMBER', 90, 'LAB', ''),
    ('М-СЕПТЕМВРИ', 'M', 'SEPTEMBER', 90, 'LAB', ''),
    ('ЕМТ-СЕПТЕМВРИ', 'EMT', 'SEPTEMBER', 90, 'LAB', ''),
    ('АОК-СЕПТЕМВРИ', 'AOK', 'SEPTEMBER', 90, 'LAB', ''),
    ('УНД-СЕПТЕМВРИ', 'UND', 'SEPTEMBER', 90, 'LAB', ''),
    ('ЕТХАК-СЕПТЕМВРИ', 'ETHAK', 'SEPTEMBER', 90, 'LAB', ''),
    ('КОМПАРХ-СЕПТЕМВРИ', 'KOMPARH', 'SEPTEMBER', 90, 'LAB', ''),
    ('СКТ-СЕПТЕМВРИ', 'SKT', 'SEPTEMBER', 90, 'LAB', ''),
    ('ОС-СЕПТЕМВРИ', 'OS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДИСКСТРУК2-СЕПТЕМВРИ', 'DISSTRUC2', 'SEPTEMBER', 90, 'LAB', ''),
    ('СОФТИНЖ-СЕПТЕМВРИ', 'SOFTENG', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДИЧК-СЕПТЕМВРИ', 'DICK', 'SEPTEMBER', 90, 'LAB', ''),
    ('БИЗСТАТ-СЕПТЕМВРИ', 'BIZSTAT', 'SEPTEMBER', 90, 'LAB', ''),
    ('ДИГБИБ-СЕПТЕМВРИ', 'DIGBIB', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВИРТ-СЕПТЕМВРИ', 'VIRT', 'SEPTEMBER', 90, 'LAB', ''),
    ('ВИ-СЕПТЕМВРИ', 'VI', 'SEPTEMBER', 90, 'LAB', ''),
    ('ИТСУ-СЕПТЕМВРИ', 'ITSU', 'SEPTEMBER', 90, 'LAB', ''),
    ('МАТ2-СЕПТЕМВРИ', 'MAT2', 'SEPTEMBER', 90, 'LAB', ''),
    ('АДСБ-СЕПТЕМВРИ', 'ADSB', 'SEPTEMBER', 90, 'LAB', '');


-- MASTERS STUDIES
INSERT INTO exam_definition (id, subject_abbreviation, exam_session, duration_minutes, type, note)
VALUES
    ('DEVOPS_SD-SEPTEMBER', 'DEVOPS_SD', 'SEPTEMBER', 90, 'LAB', ''),
    ('SLM-SEPTEMBER', 'SLM', 'SEPTEMBER', 90, 'LAB', ''),
    ('SDP-SEPTEMBER', 'SDP', 'SEPTEMBER', 90, 'LAB', ''),
    ('MBSE-SEPTEMBER', 'MBSE', 'SEPTEMBER', 90, 'LAB', ''),
    ('ACG-SEPTEMBER', 'ACG', 'SEPTEMBER', 90, 'LAB', ''),
    ('AADIS-SEPTEMBER', 'AADIS', 'SEPTEMBER', 90, 'LAB', ''),
    ('APVS-SEPTEMBER', 'APVS', 'SEPTEMBER', 90, 'LAB', ''),
    ('DATAVIZ-SEPTEMBER', 'DATAVIZ', 'SEPTEMBER', 90, 'LAB', ''),
    ('VGDVIZ-SEPTEMBER', 'VGDVIZ', 'SEPTEMBER', 90, 'LAB', ''),
    ('BIOMSYS-SEPTEMBER', 'BIOMSYS', 'SEPTEMBER', 90, 'LAB', ''),
    ('BIZD-SEPTEMBER', 'BIZD', 'SEPTEMBER', 90, 'LAB', ''),

    ('AMWAPPS-SEPTEMBER', 'AMWAPPS', 'SEPTEMBER', 90, 'LAB', ''),
    ('FM-SEPTEMBER', 'FM', 'SEPTEMBER', 90, 'LAB', ''),
    ('MEDINFO-SEPTEMBER', 'MEDINFO', 'SEPTEMBER', 90, 'LAB', ''),
    ('AENGSR-SEPTEMBER', 'AENGSR', 'SEPTEMBER', 90, 'LAB', ''),
    ('RMWT-SEPTEMBER', 'RMWT', 'SEPTEMBER', 90, 'LAB', ''),
    ('DSEE-SEPTEMBER', 'DSEE', 'SEPTEMBER', 90, 'LAB', ''),
    ('SECS-SEPTEMBER', 'SECS', 'SEPTEMBER', 90, 'LAB', ''),
    ('MULTMODINT-SEPTEMBER', 'MULTMODINT', 'SEPTEMBER', 90, 'LAB', ''),
    ('SOFTARCH-SEPTEMBER', 'SOFTARCH', 'SEPTEMBER', 90, 'LAB', ''),
    ('DSIOT-SEPTEMBER', 'DSIOT', 'SEPTEMBER', 90, 'LAB', ''),
    ('SOFREL-SEPTEMBER', 'SOFREL', 'SEPTEMBER', 90, 'LAB', ''),
    ('ENGETH-SEPTEMBER', 'ENGETH', 'SEPTEMBER', 90, 'LAB', '');

-- PHD STUDIES
INSERT INTO exam_definition (id, subject_abbreviation, exam_session, duration_minutes, type, note)
VALUES
    ('ASCS-SEPTEMBER', 'ASCS', 'SEPTEMBER', 90, 'LAB', ''),
    ('ASST-SEPTEMBER', 'ASST', 'SEPTEMBER', 90, 'LAB', ''),
    ('BIOI-SEPTEMBER', 'BIOI', 'SEPTEMBER', 90, 'LAB', ''),
    ('ESTC-SEPTEMBER', 'ESTC', 'SEPTEMBER', 90, 'LAB', ''),
    ('EVVSR-SEPTEMBER', 'EVVSR', 'SEPTEMBER', 90, 'LAB', ''),
    ('ATCSHPC-SEPTEMBER', 'ATCSHPC', 'SEPTEMBER', 90, 'LAB', ''),
    ('PRACCRYPTO-SEPTEMBER', 'PRACCRYPTO', 'SEPTEMBER', 90, 'LAB', ''),
    ('AIWS-SEPTEMBER', 'AIWS', 'SEPTEMBER', 90, 'LAB', ''),
    ('BDA-SEPTEMBER', 'BDA', 'SEPTEMBER', 90, 'LAB', ''),
    ('AWNET-SEPTEMBER', 'AWNET', 'SEPTEMBER', 90, 'LAB', ''),
    ('AMIS-SEPTEMBER', 'AMIS', 'SEPTEMBER', 90, 'LAB', ''),
    ('NITT-SEPTEMBER', 'NITT', 'SEPTEMBER', 90, 'LAB', ''),
    ('CPBIOINFO-SEPTEMBER', 'CPBIOINFO', 'SEPTEMBER', 90, 'LAB', ''),
    ('SDS-SEPTEMBER', 'SDS', 'SEPTEMBER', 90, 'LAB', '');








